# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# JournalEntry.destroy_all
# Journal.destroy_all

JournalEntry.destroy_all
Journal.destroy_all
User.destroy_all

testuser = User.create(email: "hello@gmail.com", phone_number: '+19149074672', zipcode: "10501", password: "123456", ok_to_contact: true)

anna = User.create(email: "anna@gmail.com", phone_number: '+16466441998', zipcode: "10583", password: "123456", ok_to_contact: true)

testuser2 = User.create(email: "flatironstudent@gmail.com",phone_number: '+19149074672', zipcode: "90037", password: "123456", ok_to_contact: true)

coronavirus = Journal.create(title: "coronavirus", user: testuser)
coronavirus2 = Journal.create(title: "coronavirus", user: anna)
coronavirus3 = Journal.create(title: "coronavirus", user: testuser2)

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-02 18:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '11211')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-07 15:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '11210')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-08 15:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '11211')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-06 15:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10519')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-04 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '11211')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-03 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10011')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-02 18:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10002')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-01 15:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10002')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-03-31 15:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10002')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-03-30 15:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10002')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-04 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10002')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-05 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10002')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-06 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-08 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-09 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-04 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-05 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-06 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-08 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-09 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-10 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-10 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-02 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus, 
created_at: "2020-04-01 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-05 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-06 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-06 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-06 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-06 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-06 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-0713:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus2, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '10014' )

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90037')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-09 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-08 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-09 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-10 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06", zipcode: '90001')

JournalEntry.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas volutpat blandit aliquam etiam erat. Mi tempus imperdiet nulla malesuada. Non arcu risus quis varius quam quisque id. Nisi lacus sed viverra tellus in. Massa vitae tortor condimentum lacinia quis. Ultricies lacus sed turpis tincidunt id aliquet risus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper viverra nam libero justo laoreet sit amet. Sed vulputate odio ut enim blandit volutpat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Amet consectetur adipiscing elit ut aliquam purus. Porttitor rhoncus dolor purus non enim praesent elementum. Diam maecenas sed enim ut sem viverra. Sagittis vitae et leo duis ut diam quam nulla. Risus ultricies tristique nulla aliquet. Ut pharetra sit amet aliquam. Eu augue ut lectus arcu bibendum at varius vel.", sentiment: rand(-1.0..1.0), magnitude: rand(-1.0..1.0), journal: coronavirus3, 
created_at: "2020-04-07 13:12:06", updated_at: "2020-03-16 13:12:06",  zipcode: '90001')


